### PR TITLE
Move easy functions to FFI

### PR DESCRIPTION
**Pull request by seanhandley**
Here's the trivial functions that don't need structs/string pointers etc.

### Note

I had to convert the installed `libh3.a` (static archive) to a `.so` (dynamic shared object).

```bash
$ cd /usr/local/lib
$ mkdir tmp
$ cp libh3.a tmp/
$ cd tmp/
$ ar -x libh3.a
20:24 /usr/local/lib/tmp 2.5.0
$ ls
__.SYMDEF SORTED	bbox.c.o		geoCoord.c.o		libh3.a			mathExtensions.c.o	vec3d.c.o
algos.c.o		coordijk.c.o		h3Index.c.o		linkedGeo.c.o		polygon.c.o		vertexGraph.c.o
baseCells.c.o		faceijk.c.o		h3UniEdge.c.o		localij.c.o		vec2d.c.o
$ gcc -shared *.o -o libh3.so
20:25 /usr/local/lib/tmp 2.5.0
$ cp libh3.so ..
```

I like the FFI syntax and it's clearly more maintainable but I'm concerned about how best to deal with the `.so` issue.

When people install `h3` from source as instructed on the README, it won't by default be a SO.

So how do we handle this?

cc @fxn @supagroova 

EDIT: Fixed 😁 See below.

### CODE REVIEW

**Comment by seanhandley** [comment]
Thanks @dfellis !

For now I've updated the README but that's a good idea. I'll follow up with it through the week.

**Comment by fxn** [comment]
Pretty neat man! Let me suggest a couple things.

On one hand, I believe the public interface could be generated on the spot using the version of `attach_function` that [allows you to choose a function name](https://github.com/ffi/ffi/wiki/Basic-Usage#hello-windows-using-ffi). Off the top of my head (untested):

```ruby

private def underscore(h3method)
  snake_cased = h3method.to_s.gsub(/([a-z\d])([A-Z])/) do
    $1 + "_" + $2.downcase
  end
  [snake_cased, h3method]
end

attach_function *underscore(:h3Distance), [ H3_INDEX, H3_INDEX], :int
```


On the other hand, FFI supports a [`bool` type](https://github.com/ffi/ffi/wiki/Types). I have never used it, but set as return type, I would expect FFI to return a boolean in Ruby land automatically for you. Maybe worth testing if that is the case to save the `!= 0`s.

**Comment by fxn** [comment]
Ah, if `bool` works, then you could additionally have

```ruby
private def predicate(h3method)
  # maniputlate underscore(h3method) + "?"
end
```

and call that one instead of `underscore` for predicates.

**Comment by seanhandley** [comment]
Thanks @fxn ! I'll give that a try.

**Pull request merged**
